repositories:
- remal/gsheet-project

transformations:
- name: .gitattributes
  format: text
  includes:
  - .gitattributes
  script: |
    return content
        + [
            '',
            '# gsheet-project:',
            '/dist/** -diff linguist-generated=true',
            '',
        ].join('\n')
- name: .gitignore
  format: text
  includes:
  - .gitignore
  script: |
    return content
        + [
            '',
            '# gsheet-project:',
            '/.pnp.*',
            '/.yarn/*',
            '!/.yarn/patches/',
            '!/.yarn/plugins/',
            '!/.yarn/releases/',
            '!/.yarn/sdks/',
            '!/.yarn/versions/',
            '/build',
            '/coverage',
            '',
        ].join('\n')
- name: .github/sync-with-template.yml
  format: yaml
  includes:
  - .github/sync-with-template.yml
  script: |
    ;[
      '.yarn/**',
      'check-dependency-engines.*js',
      'update-node-version-in-files.*js',
    ].forEach(path => {
      if (!content.includes.includes(path)) {
        content.includes.push(path)
      }
    })
    return content
- name: .github/workflows/codespell.yml
  format: text
  includes:
  - .github/workflows/codespell.yml
  script: |
    return content
      .replace(/((\n[ ]+)check_hidden: '[^']*')/, "$1$2skip: './dist/**,./.yarn/**'")
- name: Renovate
  format: text
  includes:
  - .github/renovate.json5
  replaceWithText: |
    {
      $schema: "https://docs.renovatebot.com/renovate-schema.json",
      extends: ["github>remal/renovate-config:global"],

      "git-submodules": {
        enabled: false, // This is in beta for now, so let's use Dependabot to update Git submodules
      },

      constraintsFiltering: "strict",
      // $$$sync-with-template-modifiable: constraints $$$
      // $$$sync-with-template-modifiable-end$$$
    }
