name: build

on:
  push:
    branches:
    - main
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: build-${{github.ref}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1


    - name: Read action's Node.js version
      id: readNodeVersion
      run: |
        VERSION=$( cat .nvmrc )
        VERSION=$( echo -e "${VERSION}" | tr -d '[:space:]' )
        if [[ "$VERSION" =~ ^v[0-9]+$ ]]; then
          VERSION=${VERSION:1}
        fi
        echo "Action's Node.js version: $VERSION"
        echo "result=$VERSION" >> $GITHUB_OUTPUT

    - name: Setup Node.js ${{steps.readNodeVersion.outputs.result}}
      uses: actions/setup-node@v4
      with:
        node-version: '${{steps.readNodeVersion.outputs.result}}'

    - name: Update Node.js version in project files
      run: |
        node update-node-version-in-files "${{steps.readNodeVersion.outputs.result}}"

    - name: Enable Corepack
      run: |
        corepack enable


    - name: Restore node_modules cache
      id: restore-node_modules-cache
      uses: actions/cache/restore@v4
      with:
        key: ${{runner.os}}-node_modules-${{hashFiles('package.json', 'yarn.lock', '.yarnrc.yml', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
        path: |
          .yarn
          node_modules

    - name: Install dependencies
      run: |
        yarn install --no-immutable

    - name: Save node_modules cache
      if: steps.restore-node_modules-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{runner.os}}-node_modules-${{hashFiles('package.json', 'yarn.lock', '.yarnrc.yml', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
        path: |
          .yarn
          node_modules


    - name: Build
      run: |
        yarn run dist


    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && env.PUSH_BACK_TOKEN}}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        message: '[push-back] Push-back updated files during build'
